services:
  - type: web
    name: ecommerce-product-api
    env: node
    buildCommand: npm install
    startCommand: node app.js
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
